/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Disciplina;
import model.dao.DisciplinaDAO;

/**
 *
 * @author Eduardo Soares
 */
public class TelaPesquisaDisciplinaMDI extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaPesquisaAlunoMDI
     */
    public TelaPesquisaDisciplinaMDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfDatafim = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        tfSemestre = new javax.swing.JTextField();
        tfDatainicio = new javax.swing.JTextField();
        tfCodigo = new javax.swing.JTextField();
        tfCodigocurso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tableDisciplinas = new javax.swing.JTable();

        jPasswordField1.setText("jPasswordField1");

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));

        jLabel1.setText("Codigo");

        jLabel2.setText("Nome");

        jLabel3.setText("Data Fim");

        jLabel6.setText("Data Inicio");

        jButton3.setText("Pesquisar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Salvar Alterações");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Deletar Disciplina");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        tfSemestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSemestreActionPerformed(evt);
            }
        });

        tfDatainicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDatainicioActionPerformed(evt);
            }
        });

        tfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodigoActionPerformed(evt);
            }
        });

        tfCodigocurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodigocursoActionPerformed(evt);
            }
        });

        jLabel4.setText("Semestre");

        jLabel5.setText("Codigo do Curso");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(54, 54, 54)
                .addComponent(jButton5)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfCodigo)
                    .addComponent(jLabel6)
                    .addComponent(tfDatainicio, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tfDatafim, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCodigocurso, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCodigocurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jButton3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfDatainicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfDatafim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(14, 14, 14)
                        .addComponent(jButton4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)))
                .addContainerGap())
        );

        tableDisciplinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Semestre", "Data Inicio", "Data Fim", "Codigo do Curso"
            }
        ));
        tableDisciplinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDisciplinasMouseClicked(evt);
            }
        });
        tableDisciplinas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableDisciplinasKeyReleased(evt);
            }
        });
        jScrollPane10.setViewportView(tableDisciplinas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(240, 180, 921, 492);
    }// </editor-fold>//GEN-END:initComponents

    private void tableDisciplinasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableDisciplinasKeyReleased

        if (tableDisciplinas.getSelectedRow() != -1) {
            tfCodigo.setText(tableDisciplinas.getValueAt(tableDisciplinas.getSelectedRow(), 0).toString());
            tfNome.setText(tableDisciplinas.getValueAt(tableDisciplinas.getSelectedRow(), 1).toString());
            tfSemestre.setText(tableDisciplinas.getValueAt(tableDisciplinas.getSelectedRow(), 2).toString());
            tfDatainicio.setText(tableDisciplinas.getValueAt(tableDisciplinas.getSelectedRow(), 3).toString());
            tfDatafim.setText(tableDisciplinas.getValueAt(tableDisciplinas.getSelectedRow(), 4).toString());
            tfCodigocurso.setText(tableDisciplinas.getValueAt(tableDisciplinas.getSelectedRow(), 5).toString());
        }
    }//GEN-LAST:event_tableDisciplinasKeyReleased

    private void tableDisciplinasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDisciplinasMouseClicked

        if (tableDisciplinas.getSelectedRow() != -1) {
            tfCodigo.setText(tableDisciplinas.getValueAt(tableDisciplinas.getSelectedRow(), 0).toString());
            tfNome.setText(tableDisciplinas.getValueAt(tableDisciplinas.getSelectedRow(), 1).toString());
            tfSemestre.setText(tableDisciplinas.getValueAt(tableDisciplinas.getSelectedRow(), 2).toString());
            tfDatainicio.setText(tableDisciplinas.getValueAt(tableDisciplinas.getSelectedRow(), 3).toString());
            tfDatafim.setText(tableDisciplinas.getValueAt(tableDisciplinas.getSelectedRow(), 4).toString());
            tfCodigocurso.setText(tableDisciplinas.getValueAt(tableDisciplinas.getSelectedRow(), 5).toString());
        }
    }//GEN-LAST:event_tableDisciplinasMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        DisciplinaDAO dao = new DisciplinaDAO();
        Disciplina disciplina = dao.selecionar(Integer.parseInt(tfCodigo.getText()));
        int i = 0;

        DefaultTableModel dtmPesquisaDisciplinas = (DefaultTableModel) tableDisciplinas.getModel();
        Object[] dados = {disciplina.getCodigo(), disciplina.getNome(), disciplina.getSemestre(), disciplina.getDatainicio(), disciplina.getDatafim(), disciplina.getCodigocurso()};

        if (dtmPesquisaDisciplinas.getRowCount() > 0) {
            for (i = 0; i < dtmPesquisaDisciplinas.getRowCount(); i++) {
                if (tfCodigo.getText().equals(dtmPesquisaDisciplinas.getValueAt(i, 0))) {
                    JOptionPane.showMessageDialog(null, "Disciplina já registrado em tabela.");
                    break;
                }
            }
        }
        if (disciplina.getCodigo() <= 0){
            JOptionPane.showMessageDialog(null, "Disciplina não cadastrada!");
        }
        else if (i >= dtmPesquisaDisciplinas.getRowCount()){
            dtmPesquisaDisciplinas.addRow(dados);
        }  

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        DisciplinaDAO dao = new DisciplinaDAO();
        dao.deletar(Integer.parseInt(tfCodigo.getText()));

        if (tableDisciplinas.getSelectedRow() != -1) {
            DefaultTableModel dtmPesquisaDisciplinas = (DefaultTableModel) tableDisciplinas.getModel();
            dtmPesquisaDisciplinas.removeRow(tableDisciplinas.getSelectedRow());
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum registo selecionado.");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        DisciplinaDAO dao = new DisciplinaDAO();
        Disciplina disciplina = new Disciplina();
        int oldcodigo = Integer.parseInt(tableDisciplinas.getValueAt(tableDisciplinas.getSelectedRow(), 0).toString());

        disciplina.setCodigo(Integer.parseInt(tfCodigo.getText()));
        disciplina.setNome(tfNome.getText());
        disciplina.setSemestre(Integer.parseInt(tfSemestre.getText()));
        disciplina.setDatainicio(tfDatainicio.getText());
        disciplina.setDatafim(tfDatafim.getText());
        disciplina.setSemestre(Integer.parseInt(tfCodigocurso.getText()));

        dao.alterar(disciplina, oldcodigo);
        
        DefaultTableModel dtmPesquisaDisciplinas = (DefaultTableModel) tableDisciplinas.getModel();
        Object[] dados = {disciplina.getCodigo(), disciplina.getNome(), disciplina.getSemestre(), disciplina.getDatainicio(), disciplina.getDatafim(), disciplina.getCodigocurso()};
        dtmPesquisaDisciplinas.insertRow(tableDisciplinas.getSelectedRow(), dados);
        dtmPesquisaDisciplinas.removeRow(tableDisciplinas.getSelectedRow() + 1);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void tfDatainicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDatainicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDatainicioActionPerformed

    private void tfSemestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSemestreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSemestreActionPerformed

    private void tfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigoActionPerformed

    private void tfCodigocursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodigocursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigocursoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JTable tableDisciplinas;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfCodigocurso;
    private javax.swing.JTextField tfDatafim;
    private javax.swing.JTextField tfDatainicio;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfSemestre;
    // End of variables declaration//GEN-END:variables
}
